### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by standrd** [SamSlotemaker/warzone-teamfinder#1]
### Repository
* Description is kort, maar wel duidelijk. Ik zie vanuit de table of contents dat het concept later nog verder beschreven wordt
* Live demo is aanwezig en werkt!
* Informatie om te installeren is aanwezig
* Er is een mooie visuele beschrijving van de delen van de API die je gebruikt, wat goed werkt
* De data flow chart is een beetje kaal, het zou handig zijn als sockets verbindingen bijv een andere kleur krijgen dan API calls
* Beschrijving van real-time events ontbreekt nog

### Concept
* Je legt bij het kopje concept meer functionaliteiten uit. Ik denk dat het handig is om eerst een paragraafje te schrijven puur over waarom de app bestaat, en daarna verder uitleg geven over de functionaliteiten.
* Functionaliteiten die je beschrijft zijn duidelijk, ook de MOSCOW die eronder staat maakt het extra duidelijk
* Ik had moeite met inloggen, ik had mijn Battle net op public gezet, maar ik kon nog niet inloggen. Misschien dat ik zelf iets fout deed, maar hierdoor kon ik niet echt testen. Misschien is het een optie om op een soort guest account er toch in te kunnen?

### Data life cycle
Zoals ik al eerder beschreef, vind ik dat hij nog iets duidelijker kan worden door meer met kleur te doen. Ik vind hem wel erg uitgebreid en ik geloof zeker dat alle informatie erin verwerkt zit.

### Real-time events
Nog niet aanwezig.

### API info
Er is een diagram waarin je uitlegt welke GET responses je krijgt. Het zou handig zijn om in je README nog de endpoints met geschreven uitleg erbij te zetten, in plaats van alleen een link naar de docs.

### Code comments
* Ik zou API calls & socket io een beetje uit elkaar halen zodat de server.js overzichtelijker wordt
* Lijkt erop dat je zelfs al een database hebt draaien, je schiet al aardig op!
* Ik zie inconsistentie in gebruik van ';' of juist niet aan het einde van regels

**Comment by SamSlotemaker** [comment]
desciption expanded, live events added, api endpoint added, code consistency fixed
