### ISSUE TITLE
Error height is kinda heigh :(

### ISSUE THREAD

**Issue by RowinRuizendaal** [SamSlotemaker/warzone-teamfinder#14]
After entering a invalid account name:

![image](https://user-images.githubusercontent.com/33514521/115842215-e3ee8a80-a41d-11eb-8e05-5fc8064ace52.png)

![image](https://user-images.githubusercontent.com/33514521/115842327-fff22c00-a41d-11eb-8015-df94d257db2e.png)

I have to scroll to get back to the form

**Comment by SamSlotemaker** [comment]
whooops fixed
