### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by RowinRuizendaal** [SamSlotemaker/warzone-teamfinder#2]
#### Does the repo have an apt description? ✔️

yes the repo consists of an app description

#### Is there a link to the live demo at the top? ✔️

Yes, there is a link to the live demo ps: you might change the title from spacecoders team chat to your app title :)

#### Are any files in the repo that shouldn't be there like a .env file or node_modules? ✔️

Nope, I could not find anything in the repo

#### Is there a section about the concept, install notes, data life cycle, external API, and real-time events? ✔️

Yes, everything is well written.

#### Read about the concept in the readme, do you understand what the app does? ✔️ 

Yes, although I am not sure if you can extend the description, your description is short but it makes sense for me, I am not sure if other people will understand what you mean with that short sentence (concept)

#### Open up the live link (if it's already alive) and play around with the app ✔️

Interesting concept although maybe it is cool to leave a demo as a placeholder or w/e comes to mind for the users that want to try out your concept but do not have an account on a certain platform.

#### Understand the data life cycle ✔️

The life cycle is well written and gives me a better view of what the app can do and how the event is going

> real-time-data is not available

#### Api info  ✔️

The API is described, and you also mentioned the data that you are receiving from the API

**Comment by SamSlotemaker** [comment]
changed title, added more detailed description, added playstation account in readme to test the app
